### ISSUE TITLE
INTERVAL WEEK is having issue.

### ISSUE THREAD

**Issue by pamboo80** [rockset/community#16]
Just copy and paste the sample query as in our document (https://docs.rockset.com/date-and-time-functions/#date-functions) and execute, it will fail.
SELECT
    CURRENT_DATE() AS today,
    (CURRENT_DATE() - INTERVAL 1 WEEK) AS last_week
I was executing some other query like below with respect to same INTERVAL WEEK and felt we are not supporting WEEK. But document looks like we do support WEEK, but having some bug/issues I feel.
   SELECT (DATE(2020,12,17) + 1 * INTERVAL '1 month') AS outMonth (No issues)
   SELECT (DATE(2020,12,17) + 1 * INTERVAL '1 day') AS outDay (No issues)
   SELECT (DATE(2020,12,17) + 1 * INTERVAL '1 week') AS outWeek (This query will fail)

**Comment by benhannel** [comment]
Support for that syntax will be available in production very soon. For now, you can use `INTERVAL '7 DAY'`.

**Comment by pamboo80** [comment]
Fixed.
