### ISSUE TITLE
INTERVAL is not handling fractions. 

### ISSUE THREAD

**Issue by pamboo80** [rockset/community#17]
INTERVAL is not handling fractions. It is rounding to the nearest integer value.
For e.g.
SELECT DATETIME(DATE '2020-01-01', TIME '06:20:22') + (1.2 * INTERVAL '1 DAY')   will add one day to the Date specified.
SELECT DATETIME(DATE '2020-01-01', TIME '06:20:22') + (1.5 * INTERVAL '1 DAY')   will add two days to the Date specified.
But the fractions are not rounded into correct hours, minutes and seconds . They just rounding off the interval input value itself before applying to the date.
SELECT DATETIME(DATE '2020-01-01', TIME '06:20:22') + (1.5 * INTERVAL '1 DAY')  should output '2020-01-02 18:20:22' . But our query will output  '2020-01-03 06:20:22'.  So, with our queries it is not possible to do a fractional interval date time.

**Comment by benhannel** [comment]
Thank you for reporting this. The fix will be deployed soon.
