### ISSUE TITLE
 Issue in Division (/) operator

### ISSUE THREAD

**Issue by pamboo80** [rockset/community#18]
There is some issue in division operator . First it is not decimal precision and also returns no rows. Some fraction error there.
Run the following queries to see this.
SELECT 1/(0.2) [ This will work right ]
SELECT 1/(0.3) [ No rows will return ]
SELECT cast(1 as float) /cast(0.3 as float) [ This too will return no rows]
SELECT (86400+3600) / (60 * 60 * 24)  [ Only integer result. No decimal precision ]
SELECT (86400+3600) / (60.0 * 60 * 24) [ In fact this will return no rows ]

**Comment by benhannel** [comment]
Thank you for reporting this issue. We're looking into it. This issue only affects the web console. If you use any of our client SDKs or the REST API, you should receive correct results.

**Comment by pamboo80** [comment]
But actually, I ran through Java-client JDBC driver. I m not sure about the rows that are not returning in console (So I came to console to check first, as precision was not happening in division through queries via JDBC) and happen to see empty rows too. Can I send more details like my account as it got the collection in which I ran the queries via Email so that you can check from your side? Thanks.

**Comment by benhannel** [comment]
We were able to reproduce this on our end in the console. What exactly did you see with the JDBC driver? Did it return no rows, or an error?

**Comment by pamboo80** [comment]
No error. Rows are returned. But no decimal precision. 

Say when I divide a micro second interval with  this value 1.0 * (60.0 * 60 * 24) , for float casting I added 1.0 * again. In fact divide by (60.0 * 60 * 24) value for a micro second interval, no decimal precision is coming. The answer is integer only though fraction parts possible when it divide. 

Note: I used DURATION_MICROS first to get the value from the microsecond_interval data type. Even tried this logic to get the interval and divide  i.e UNIX_SECONDS(TIMESTAMP(DATE(1970,1,1)+(date1 - TIMESTAMP(datetime1))) / 1.0 * (60.0 * 60 * 24) , but no decimal precision was coming.

**Comment by pamboo80** [comment]
I felt it might prefect divide and hence checked with 61.0 I guess and it failed. I will run the query again through the SDK and let you know is precision coming. 5 minutes. Sorry.

**Comment by pamboo80** [comment]
Sorry, precision is coming when calling from SDK. Looks like I tested dividing by (60.1 * 60 * 24) on the console while debugging the error. Excuse me for that.

**Comment by benhannel** [comment]
Ok, thank you for letting us know. We're investigating the console issue.

**Comment by pamboo80** [comment]
Sure, Thanks.

**Comment by pamboo80** [comment]
Fixed.
