### ISSUE TITLE
add support to convert JSON encoded strings to advanced types and back

### ISSUE THREAD

**Issue by veeve** [rockset/community#6]
In many situations, nested objects and nested arrays are converted into a JSON-encoded string before they are stored in services such as S3. When such data sets are loaded back into Rockset, these fields show up as strings and do not get translated into advanced types such as nested objects, nested arrays etc in Rockset. because of this, such string fields do not benefit from most of Rockset's features such as automatic schematization, and converged indexing.

if Rockset can implement the equivalent of Python's json.loads() and json.dumps() then this can be solved easily by using field-mappings.

desired behavior: 

- [ ] add 2 new built in functions JSON_LOADS() and JSON_DUMPS()
- [ ] JSON_LOADS() should take a single input argument of type string and then return a value of the appropriate advanced Rockset type. 
    eg:  `select typeof(json_loads('[1, 2, 3]'))` should return `'array'` while `select typeof(json_loads('{"k": "v"}'))` should return `'object'`
- [ ] do the inverse for JSON_DUMPS() which should take a single input argument that could be of any type supported by Rockset and return a single string result.
- [ ] `SELECT X = JSON_LOADS(JSON_DUMPS(X))` should always return True
- [ ] Rockset type objects should be natively supported -- eg: `SELECT JSON_LOADS('{"__rockset_type": "TIMESTAMP", ...}')` should return a value of Rockset type TIMESTAMP.

**Comment by timothyquach** [comment]
Thanks!

**Comment by veeve** [comment]
thanks for working on this @sandeepgd!

**Comment by sandeepgd** [comment]
This has been fixed and pushed to production. Closing the issue.
